version: "3"
services:
    mysql_db:
      container_name: demo_app_db
      image: mysql
      ports:
        - "3306:3306"  
      environment:
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=my123_sql456
      restart: unless-stopped  
      volumes:
        - ./scripts/db_dump_20210826.sql:/docker-entrypoint-initdb.d/0_init.sql